//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyClient_Stats.RoutingSoapReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingSoapReference.IRoutingSoap")]
    public interface IRoutingSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingSoap/computePath", ReplyAction="http://tempuri.org/IRoutingSoap/computePathResponse")]
        ClassLibrary.ResultObject computePath(string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingSoap/computePath", ReplyAction="http://tempuri.org/IRoutingSoap/computePathResponse")]
        System.Threading.Tasks.Task<ClassLibrary.ResultObject> computePathAsync(string start, string end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingSoapChannel : HeavyClient_Stats.RoutingSoapReference.IRoutingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingSoapClient : System.ServiceModel.ClientBase<HeavyClient_Stats.RoutingSoapReference.IRoutingSoap>, HeavyClient_Stats.RoutingSoapReference.IRoutingSoap {
        
        public RoutingSoapClient() {
        }
        
        public RoutingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClassLibrary.ResultObject computePath(string start, string end) {
            return base.Channel.computePath(start, end);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary.ResultObject> computePathAsync(string start, string end) {
            return base.Channel.computePathAsync(start, end);
        }
    }
}
