//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyClient_Stats.RoutingSoapReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultObject", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
    [System.SerializableAttribute()]
    public partial class ResultObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient_Stats.RoutingSoapReference.PositionInstruction footToFootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient_Stats.RoutingSoapReference.PositionInstruction footToStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient_Stats.RoutingSoapReference.PositionInstruction sationToFootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient_Stats.RoutingSoapReference.Position startPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient_Stats.RoutingSoapReference.PositionInstruction stationToSationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool worthItField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient_Stats.RoutingSoapReference.PositionInstruction footToFoot {
            get {
                return this.footToFootField;
            }
            set {
                if ((object.ReferenceEquals(this.footToFootField, value) != true)) {
                    this.footToFootField = value;
                    this.RaisePropertyChanged("footToFoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient_Stats.RoutingSoapReference.PositionInstruction footToStation {
            get {
                return this.footToStationField;
            }
            set {
                if ((object.ReferenceEquals(this.footToStationField, value) != true)) {
                    this.footToStationField = value;
                    this.RaisePropertyChanged("footToStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient_Stats.RoutingSoapReference.PositionInstruction sationToFoot {
            get {
                return this.sationToFootField;
            }
            set {
                if ((object.ReferenceEquals(this.sationToFootField, value) != true)) {
                    this.sationToFootField = value;
                    this.RaisePropertyChanged("sationToFoot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient_Stats.RoutingSoapReference.Position startPosition {
            get {
                return this.startPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.startPositionField, value) != true)) {
                    this.startPositionField = value;
                    this.RaisePropertyChanged("startPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient_Stats.RoutingSoapReference.PositionInstruction stationToSation {
            get {
                return this.stationToSationField;
            }
            set {
                if ((object.ReferenceEquals(this.stationToSationField, value) != true)) {
                    this.stationToSationField = value;
                    this.RaisePropertyChanged("stationToSation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool worthIt {
            get {
                return this.worthItField;
            }
            set {
                if ((this.worthItField.Equals(value) != true)) {
                    this.worthItField = value;
                    this.RaisePropertyChanged("worthIt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PositionInstruction", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
    [System.SerializableAttribute()]
    public partial class PositionInstruction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient_Stats.RoutingSoapReference.Step[] instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient_Stats.RoutingSoapReference.Position[] positionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient_Stats.RoutingSoapReference.Step[] instructions {
            get {
                return this.instructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.instructionsField, value) != true)) {
                    this.instructionsField = value;
                    this.RaisePropertyChanged("instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient_Stats.RoutingSoapReference.Position[] positions {
            get {
                return this.positionsField;
            }
            set {
                if ((object.ReferenceEquals(this.positionsField, value) != true)) {
                    this.positionsField = value;
                    this.RaisePropertyChanged("positions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Step", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
    [System.SerializableAttribute()]
    public partial class Step : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                if ((this.distanceField.Equals(value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instruction {
            get {
                return this.instructionField;
            }
            set {
                if ((object.ReferenceEquals(this.instructionField, value) != true)) {
                    this.instructionField = value;
                    this.RaisePropertyChanged("instruction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingSoapReference.IRoutingSoap")]
    public interface IRoutingSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingSoap/computePath", ReplyAction="http://tempuri.org/IRoutingSoap/computePathResponse")]
        HeavyClient_Stats.RoutingSoapReference.ResultObject computePath(string start, string end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingSoap/computePath", ReplyAction="http://tempuri.org/IRoutingSoap/computePathResponse")]
        System.Threading.Tasks.Task<HeavyClient_Stats.RoutingSoapReference.ResultObject> computePathAsync(string start, string end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingSoapChannel : HeavyClient_Stats.RoutingSoapReference.IRoutingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingSoapClient : System.ServiceModel.ClientBase<HeavyClient_Stats.RoutingSoapReference.IRoutingSoap>, HeavyClient_Stats.RoutingSoapReference.IRoutingSoap {
        
        public RoutingSoapClient() {
        }
        
        public RoutingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HeavyClient_Stats.RoutingSoapReference.ResultObject computePath(string start, string end) {
            return base.Channel.computePath(start, end);
        }
        
        public System.Threading.Tasks.Task<HeavyClient_Stats.RoutingSoapReference.ResultObject> computePathAsync(string start, string end) {
            return base.Channel.computePathAsync(start, end);
        }
    }
}
